USE custodyChain;
GO
ALTER TABLE School WITH CHECK
ADD CONSTRAINT FK_DistrictID FOREIGN KEY(DistrictID) REFERENCES District(DistrictID)
ON UPDATE CASCADE
GO 
ALTER TABLE Employee WITH CHECK
ADD CONSTRAINT FK_SchoolID FOREIGN KEY(SchoolID) REFERENCES School(SchoolID)
ON UPDATE CASCADE
GO
ALTER TABLE Student WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) REFERENCES Employee(EmployeeID)
ON UPDATE CASCADE
GO
ALTER TABLE CoC WITH CHECK
ADD CONSTRAINT FK_SchoolIDc FOREIGN KEY(SchoolID) REFERENCES School(SchoolID)
ON UPDATE CASCADE
GO
ALTER TABLE CoC WITH CHECK
ADD CONSTRAINT FK_EmployeeIDc FOREIGN KEY(EmployeeID) REFERENCES Employee(EmployeeID)
ON DELETE NO ACTION
GO
ALTER TABLE CoC WITH CHECK
ADD CONSTRAINT FK_StudentIDc FOREIGN KEY(StudentID) REFERENCES Student(StudentID)
ON DELETE NO ACTION
GO
ALTER TABLE CoC WITH CHECK
ADD CONSTRAINT FK_EquipmentIDc FOREIGN KEY(EquipmentID) REFERENCES Equipment(EquipmentID)
ON DELETE NO ACTION
GO

